// reconstructed from cp.dll
syntax = "proto2";
package ltpb;

message Settings {
  message DOF {
    required float f_num = 1;
    required float focus_depth = 2;
  }
  optional float exposure = 1;
  optional float color_temparature = 2;
  optional float color_tint = 3;
  optional float shadow_boost = 4;
  optional float highlight_boost = 5;
  optional float contrast = 6;
  optional float saturation = 7;
  optional float vibrance = 8;
  optional float clarity = 9;
  optional float blacks = 10;
  optional float whites = 11;
  optional Settings.DOF dof = 12;
  optional float sharpening = 13;
}

message Version {
  optional uint32 major = 1;
  optional uint32 minor = 2;
  optional uint32 revision = 3;
}

message Renderer {
  optional Version version = 1;
  optional Settings settings = 3;
}
